# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        core_user:
            id: app_bundle.security.user_provider.core_user
        customer:
            id: app_bundle.security.user_provider.customer
        in_memory:
            memory: ~

    encoders:
        AppBundle\Security\User\CoreUser: bcrypt
        AppBundle\Security\User\Customer: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        app:
            context: customer
            pattern: ^/app
            provider: customer
            anonymous: ~
            guard:
                authenticators:
                    - app_bundle.security.authenticator.customer
            remember_me:
                secret: "%secret%"
                lifetime: 518400
                name: __radix-application
                always_remember_me: true
        api:
            context: user
            pattern: ^/api\/1\.0
            provider: core_user
            guard:
                authenticators:
                    - app_bundle.security.authenticator.api
        main:
            context: user
            anonymous: ~
            provider: core_user
            guard:
                authenticators:
                    - app_bundle.security.authenticator.core_user
            remember_me:
                secret: "%secret%"
                lifetime: 432000
                name: __radix-core
                always_remember_me: true

    access_control:
        - { path: ^/api/1\.0, roles: [ ROLE_CORE\USER ] }
