imports:
    - { resource: services/event-subscribers.yml }
    - { resource: services/question-types.yml }

parameters: ~

services:
    app_bundle.definitions.factory:
        class: AppBundle\Definitions\DefinitionFactory
        arguments: [ "@app_bundle.question.type_manager" ]

    app_bundle.input.submission_manager:
        class: AppBundle\Input\SubmissionManager
        arguments: [ "@app_bundle.question.answer_factory" ]

    app_bundle.integrations.client.omeda:
        private: true
        class: AppBundle\Integrations\Clients\OmedaClient
        arguments: [ "@app_bundle.omeda_sdk.api_client", "@app_bundle.definitions.factory" ]

    app_bundle.integrations.handler.question_pull:
        private: true
        class: AppBundle\Integrations\Handlers\QuestionPullHandler

    app_bundle.integrations.manager:
        class: AppBundle\Integrations\IntegrationManager
        arguments: [ "@as3_modlr.store" ]
        calls:
            - [ addClient,  [ "@app_bundle.integrations.client.omeda" ] ]
            - [ addHandler, [ "@app_bundle.integrations.handler.question_pull" ] ]

    app_bundle.omeda_sdk.api_client:
        class: As3\OmedaSDK\ApiClient
