imports:
    - { resource: services/question-types.yml }

parameters: ~

services:
    app_bundle.definitions.factory:
        class: AppBundle\Definitions\DefinitionFactory
        arguments: [ "@app_bundle.question.type_manager" ]

    app_bundle.event_subscriber.keyable:
        private: true
        class: AppBundle\EventSubscriber\KeyableSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.timestampable:
        private: true
        class: AppBundle\EventSubscriber\TimestampableSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.question:
        private: true
        class: AppBundle\EventSubscriber\QuestionSubscriber
        arguments: [ "@app_bundle.question.type_manager" ]
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.integrations.client.omeda:
        private: true
        class: AppBundle\Integrations\Clients\OmedaClient
        arguments: [ "@app_bundle.omeda_sdk.api_client", "@app_bundle.definitions.factory" ]

    app_bundle.integrations.handler.question_pull:
        private: true
        class: AppBundle\Integrations\Handlers\QuestionPullHandler

    app_bundle.integrations.manager:
        class: AppBundle\Integrations\IntegrationManager
        arguments: [ "@as3_modlr.store" ]
        calls:
            - [ addClient,  [ "@app_bundle.integrations.client.omeda" ] ]
            - [ addHandler, [ "@app_bundle.integrations.handler.question_pull" ] ]

    app_bundle.omeda_sdk.api_client:
        class: As3\OmedaSDK\ApiClient
