imports:
    - { resource: services/event-subscribers.yml }
    - { resource: services/import.yml }
    - { resource: services/question-types.yml }
    - { resource: services/security.yml }

parameters: ~

services:
    app_bundle.core.account_manager:
        class: AppBundle\Core\AccountManager
        arguments: [ "@as3_modlr.store" ]

    cygnus_platform.core.persistence_prefixer:
        private: true
        class: AppBundle\Core\PersistencePrefixer
        arguments: [ "@service_container" ]
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.core.subscriber.console:
        private: true
        class: AppBundle\Core\ConsoleSubscriber
        arguments: [ "@app_bundle.core.account_manager" ]
        tags:
            - { name: kernel.event_subscriber }

    app_bundle.core.subscriber.kernel:
        private: true
        class: AppBundle\Core\KernelSubscriber
        arguments: [ "@app_bundle.core.account_manager", "@security.http_utils" ]
        tags:
            - { name: kernel.event_subscriber }

    app_bundle.definitions.factory:
        class: AppBundle\Definitions\DefinitionFactory
        arguments: [ "@app_bundle.question.type_manager" ]

    app_bundle.input.submission_manager:
        class: AppBundle\Input\SubmissionManager
        arguments: [ "@app_bundle.question.answer_factory" ]

    app_bundle.integrations.client.omeda:
        private: true
        class: AppBundle\Integrations\Clients\OmedaClient
        arguments: [ "@app_bundle.omeda_sdk.api_client", "@app_bundle.definitions.factory" ]

    app_bundle.integrations.handler.question_pull:
        private: true
        class: AppBundle\Integrations\Handlers\QuestionPullHandler

    app_bundle.integrations.manager:
        class: AppBundle\Integrations\IntegrationManager
        arguments: [ "@as3_modlr.store" ]
        calls:
            - [ addClient,  [ "@app_bundle.integrations.client.omeda" ] ]
            - [ addHandler, [ "@app_bundle.integrations.handler.question_pull" ] ]

    app_bundle.omeda_sdk.api_client:
        class: As3\OmedaSDK\ApiClient
