application-settings-notification:
    embeds:
        support:
            type: one
            entity: application-settings-notification-email
        noreply:
            type: one
            entity: application-settings-notification-email
    attributes:
        logo:
            type: string
        name:
            type: string
