application-settings:
    embeds:
        branding:
            type: one
            entity: application-settings-branding
        notifications:
            type: one
            entity: application-settings-notifications
        support:
            type: one
            entity: application-settings-support
