# FRONT-END APPLICATION ROUTES #

app_bundle_app_auth_create:
    path: /app/auth
    defaults: { _controller: AppBundle:App\Auth:create }
    methods: [ POST ]

app_bundle_app_auth_destory:
    path: /app/auth/destroy
    methods: [ GET ]

app_bundle_app_auth_retrieve:
    path: /app/auth
    defaults: { _controller: AppBundle:App\Auth:retrieve }
    methods: [ GET ]

app_bundle_app_auth_submit:
    path: /app/auth
    methods: [ PATCH ]

app_bundle_app_optins_email_deployment:
    path: /app/opt-ins/email-deployment/{emailAddress}
    defaults: { _controller: AppBundle:App\OptIn:emailDeployment }
    methods: [ GET ]

app_bundle_app_product:
    path: /app/product/{type}
    defaults: { _controller: AppBundle:App\Product:all, type: null }
    methods: [ GET ]

app_bundle_app_product_key_or_id:
    path: /app/product/{type}/{keyOrId}
    defaults: { _controller: AppBundle:App\Product:retrieve }
    methods: [ GET ]

app_bundle_app_question_by_tag:
    path: /app/question/tag/{tagKeyOrId}
    defaults: { _controller: AppBundle:App\Question:retrieveByTag }
    methods: [ GET ]

app_bundle_app_question:
    path: /app/question/{keyOrId}
    defaults: { _controller: AppBundle:App\Question:retrieve }
    methods: [ GET ]
# @todo Submission routes should be consolidated into one.
app_bundle_app_submission_product_email_optin:
    path: /app/submission/product-email-deployment-optin
    defaults: { _controller: AppBundle:App\Submission:productEmailDeploymentOptin }
    methods: [ POST ]

app_bundle_app_submission_inquiry:
    path: /app/submission/inquiry
    defaults: { _controller: AppBundle:App\Submission:inquiry }
    methods: [ POST ]

app_bundle_app_util_country_options:
    path: /app/util/country-options
    defaults: { _controller: AppBundle:App\Utility:countryOptions }
    methods: [ GET ]

app_bundle_app_util_region_options:
    path: /app/util/region-options/{countryCode}
    defaults: { _controller: AppBundle:App\Utility:regionOptions }
    methods: [ GET ]

# LIBRARY ROUTES #

app_bundle_lib:
    path: /lib/{name}.{_format}
    defaults: { _controller: AppBundle:App\Library:index, minify: false }
    requirements:
        _format: css|js

app_bundle_lib_min:
    path: /lib/{name}.min.{_format}
    defaults: { _controller: AppBundle:App\Library:index, minify: true }
    requirements:
        _format: css|js


# CORE RELATED ROUTES #

app_bundle_auth_user_create:
    path: /auth/user/create
    defaults: { _controller: AppBundle:Auth:userCreate }
    methods: [ POST ]

app_bundle_auth_user_destroy:
    path: /auth/user/destroy

app_bundle_auth_user_retrieve:
    path: /auth/user/retrieve
    defaults: { _controller: AppBundle:Auth:userRetrieve }

app_bundle_auth_user_submit:
    path: /auth/user/submit

app_bundle_test_app:
    path: /sandbox
    defaults: { _controller: AppBundle:Sandbox:index }

# MANAGE EMBER ROUTE #

app_bundle_manage:
    path: /manage{path}
    defaults: { _controller: AppBundle:Manage:index, path: '' }
    requirements:
        path: .*
