core-application:
    entity:
        persistence:
            key: mongodb
            db: radix
    mixins: [ 'keyable', 'timestampable' ]
    attributes:
        publicKey:
            type: string
        allowedOrigins:
            type: array
            defaultValue: []
    relationships:
        account:
            type: one
            entity: core-account
        users:
            type: many
            entity: core-application-user
            inverse: true
            field: user
