services:
    app_bundle.customer.cookie_manager:
        class: AppBundle\Customer\CookieManager
        arguments: [ "@request_stack" ]

    app_bundle.customer.manager:
        class: AppBundle\Customer\CustomerManager
        arguments: [ "@app_bundle.factory.customer.account", "@app_bundle.factory.customer.identity", "@security.token_storage", "@app_bundle.security.auth.generator.customer", "@app_bundle.customer.cookie_manager", "@event_dispatcher" ]

    app_bundle.customer.subscriber:
        private: true
        class: AppBundle\Customer\CustomerSubscriber
        arguments: [ "@app_bundle.core.account_manager", "@app_bundle.customer.manager" ]
        tags:
            - { name: kernel.event_subscriber }

    app_bundle.customer.abstract_token_generator:
        abstract: true
        class: AppBundle\Customer\AbstractTokenGenerator
        arguments: [ "%secret%" ]

    app_bundle.customer.email_verify.token_generator:
        parent: app_bundle.customer.abstract_token_generator
        class: AppBundle\Customer\EmailVerifyTokenGenerator

    app_bundle.customer.password_resent.token_generator:
        parent: app_bundle.customer.abstract_token_generator
        class: AppBundle\Customer\ResetPasswordTokenGenerator
