services:
    app_bundle.customer.cookie_manager:
        class: AppBundle\Customer\CookieManager
        arguments: [ "@request_stack" ]

    app_bundle.customer.manager:
        class: AppBundle\Customer\CustomerManager
        arguments: [ "@as3_modlr.store", "@security.token_storage", "@app_bundle.security.auth.generator.customer", "@app_bundle.customer.cookie_manager" ]

    app_bundle.customer.subscriber:
        private: true
        class: AppBundle\Customer\CustomerSubscriber
        arguments: [ "@app_bundle.customer.manager" ]
        tags:
            - { name: kernel.event_subscriber }

    app_bundle.customer.email_verify.token_generator:
        class: AppBundle\Customer\EmailVerifyTokenGenerator
        arguments: [ "%secret%" ]
