services:
    app_bundle.event_subscriber.core_user:
        private: true
        class: AppBundle\EventSubscriber\CoreUserSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.customer-account:
        private: true
        class: AppBundle\EventSubscriber\CustomerAccountSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.customer_email:
        private: true
        class: AppBundle\EventSubscriber\CustomerEmailSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.keyable:
        private: true
        class: AppBundle\EventSubscriber\KeyableSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.product_website:
        private: true
        class: AppBundle\EventSubscriber\ProductWebsiteSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.timestampable:
        private: true
        class: AppBundle\EventSubscriber\TimestampableSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.question:
        private: true
        class: AppBundle\EventSubscriber\QuestionSubscriber
        arguments: [ "@app_bundle.question.type_manager" ]
        tags:
            - { name: as3_modlr.event_subscriber }
