services:
    app_bundle.event_subscriber.core_user:
        private: true
        class: AppBundle\EventSubscriber\CoreUserSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.customer_account:
        private: true
        class: AppBundle\EventSubscriber\Customer\CustomerAccountSubscriber
        calls:
            - [ setContainer, [ "@service_container" ] ]
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.customer_address:
        private: true
        class: AppBundle\EventSubscriber\Customer\CustomerAddressSubscriber
        arguments: [ "@app_bundle.factory.customer_address" ]
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.customer_answer:
        private: true
        class: AppBundle\EventSubscriber\Customer\CustomerAnswerSubscriber
        calls:
            - [ setContainer, [ "@service_container" ] ]
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.customer_email:
        private: true
        class: AppBundle\EventSubscriber\Customer\CustomerEmailSubscriber
        arguments: [ "@app_bundle.factory.customer_email" ]
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.input_submission:
        private: true
        class: AppBundle\EventSubscriber\InputSubmissionSubscriber
        arguments: [ "@request_stack", "@app_bundle.data_formatter.mongo_db" ]
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.keyable:
        private: true
        class: AppBundle\EventSubscriber\KeyableSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.product_website:
        private: true
        class: AppBundle\EventSubscriber\ProductWebsiteSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.timestampable:
        private: true
        class: AppBundle\EventSubscriber\TimestampableSubscriber
        tags:
            - { name: as3_modlr.event_subscriber }

    app_bundle.event_subscriber.question:
        private: true
        class: AppBundle\EventSubscriber\QuestionSubscriber
        arguments: [ "@app_bundle.question.type_manager" ]
        tags:
            - { name: as3_modlr.event_subscriber }
