services:
    app_bundle.subscriber_factory_manager:
        class: AppBundle\Factory\SubscriberFactoryManager
        calls:
            - [ addFactory, [ "@app_bundle.factory.customer.account" ] ]
            - [ addFactory, [ "@app_bundle.factory.customer.address" ] ]
            - [ addFactory, [ "@app_bundle.factory.customer.answer" ] ]
            - [ addFactory, [ "@app_bundle.factory.customer.email" ] ]
            - [ addFactory, [ "@app_bundle.factory.input_submission" ] ]
            - [ addFactory, [ "@app_bundle.factory.input_answer" ] ]

    app_bundle.factory.customer.account:
        class: AppBundle\Factory\Customer\CustomerAccountFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.factory.customer.address", "@app_bundle.factory.customer.phone", "@app_bundle.factory.customer.answer", "@app_bundle.factory.customer.credentials", "@app_bundle.factory.customer.email" ]

    app_bundle.factory.customer.address:
        class: AppBundle\Factory\Customer\CustomerAddressFactory
        arguments: [ "@as3_modlr.store" ]

    app_bundle.factory.customer.answer:
        class: AppBundle\Factory\Customer\CustomerAnswerFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.question.answer_factory" ]

    app_bundle.factory.customer.credentials:
        class: AppBundle\Factory\Customer\CustomerCredentialsFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.factory.customer.credentials_password", "@app_bundle.factory.customer.credentials_social" ]

    app_bundle.factory.customer.credentials_password:
        class: AppBundle\Factory\Customer\CustomerCredentialsPasswordFactory
        arguments: [ "@as3_modlr.store", "@security.password_encoder" ]

    app_bundle.factory.customer.credentials_social:
        class: AppBundle\Factory\Customer\CustomerCredentialsSocialFactory
        arguments: [ "@as3_modlr.store" ]

    app_bundle.factory.customer.email:
        class: AppBundle\Factory\Customer\CustomerEmailFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.customer.email_verify.token_generator" ]

    app_bundle.factory.customer.phone:
        class: AppBundle\Factory\Customer\CustomerPhoneFactory
        arguments: [ "@as3_modlr.store" ]

    app_bundle.factory.input_answer:
        class: AppBundle\Factory\InputAnswerFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.question.answer_factory" ]

    app_bundle.factory.input_submission:
        class: AppBundle\Factory\InputSubmissionFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.factory.input_answer", "@request_stack", "@app_bundle.data_formatter.mongo_db" ]
