services:
    app_bundle.security.api_authenticator:
        private: true
        class: AppBundle\Security\ApiAuthenticator
        arguments: [ "@as3_modlr.api.adapter" ]

    app_bundle.security.core_user_provider:
        private: true
        class: AppBundle\Security\CoreUserProvider
        arguments: [ "@as3_modlr.store" ]

    app_bundle.security.core_user_authenticator:
        private: true
        class: AppBundle\Security\CoreUserAuthenticator
        arguments: [ "@as3_modlr.api.adapter", "@security.encoder_factory" ]

    app_bundle.security.application_authenticator:
        private: true
        class: AppBundle\Security\ApplicationAuthenticator
        arguments: [ "@as3_modlr.api.adapter", "@app_bundle.core.account_manager" ]

    app_bundle.security.login_listener:
        class: AppBundle\Security\LoginListener
        arguments: [ "@security.authorization_checker", "@as3_modlr.store" ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
