services:
    app_bundle.security.authenticator.api:
        private: true
        class: AppBundle\Security\Authenticator\ApiAuthenticator
        arguments: [ "@as3_modlr.api.adapter", "@app_bundle.security.jwt.generator_manager" ]

    app_bundle.security.authenticator.application:
        private: true
        class: AppBundle\Security\Authenticator\ApplicationAuthenticator
        arguments: [ "@as3_modlr.api.adapter", "@app_bundle.core.account_manager" ]

    app_bundle.security.authenticator.core_user:
        private: true
        class: AppBundle\Security\Authenticator\CoreUserAuthenticator
        arguments: [ "@as3_modlr.api.adapter", "@security.encoder_factory" ]

    app_bundle.security.jwt.generator_manager:
        private: true
        class: AppBundle\Security\JWT\JWTGeneratorManager
        calls:
            - [ addGenerator, [ "@app_bundle.security.jwt.generator.core_user" ] ]

    app_bundle.security.jwt.generator.core_user:
        private: true
        class: AppBundle\Security\JWT\CoreUserGenerator
        arguments: [ "%secret%" ]

    app_bundle.security.login_listener:
        private: true
        class: AppBundle\Security\LoginListener
        arguments: [ "@security.authorization_checker", "@as3_modlr.store" ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    app_bundle.security.user_provider.core_user:
        private: true
        class: AppBundle\Security\User\CoreUserProvider
        arguments: [ "@as3_modlr.store" ]
